@startuml

'skinparam linetype ortho
skinparam linetype polyline
'skinparam monochrome true

skinparam package {
    backgroundColor lightgrey
}


    frame "Business Logic Layer" #orange {
        package "admin" {
            component AdministrationSystem #white {
                IAdminSession -- [AdminSession]
                IUserAccAdministration -- [UserAccAdministration]
                IReservationDbMaintenance -- [ReservationDbMaintenance]

                AdminSession --( IUserAccAdministration
                AdminSession --( IReservationDbMaintenance
            }

            component AuthenticationSystem #white {
                IAuthenticationSystem -- [UserAccountChecker]
                ISessionIdGenerator -- [SessionIdGenerator]

                UserAccountChecker --( ISessionIdGenerator
            }
        }
    }

    '##------------------------------##
    '## Business Logic to Data Layer ##
    '##------------------------------##
    IUserAccDbAccess )-- UserAccountChecker

    UserAccAdministration --( IUserAccDbAccess
    ReservationDbMaintenance --( IReservationDbAccess

@enduml