@startuml

'skinparam linetype ortho
skinparam linetype polyline
'skinparam monochrome true

skinparam package {
    backgroundColor lightgrey
}


    frame "Business Logic Layer" #orange {
        package "admin" {
            component AdministrationSystem #white {
                IAdminSession -- [AdminSession]
                [UserAccAdministration]
                [ReservationDbMaintenance]

                AdminSession --> UserAccAdministration
                AdminSession --> ReservationDbMaintenance
            }

            component AuthenticationSystem #white {
                IAuthenticationSystem -- [UserAccountChecker]
                [SessionIdGenerator]

                UserAccountChecker --> SessionIdGenerator
            }
        }
    }

    '##------------------------------##
    '## Business Logic to Data Layer ##
    '##------------------------------##
    IUserAccDbAccess )-- UserAccountChecker

    UserAccAdministration --( IUserAccDbAccess
    ReservationDbMaintenance --( IReservationDbAccess

@enduml