@startuml

'skinparam linetype ortho
skinparam linetype polyline
'skinparam monochrome true

skinparam package {
    backgroundColor lightgrey
}


    frame "Business Logic Layer" #orange {
        package "admin" {
            component AdministrationSystem #white {
                IAdminSession -- [AdminSession]

                component Maintenance #white {
                    [UserAccAdministration]
                    [ReservationDbMaintenance]
                    [RealEstateAdministration]
                    [MembershipAdministration]
                }

                AdminSession --> UserAccAdministration
                AdminSession --> ReservationDbMaintenance
                AdminSession --> RealEstateAdministration
                AdminSession --> MembershipAdministration
            }

            component AuthenticationSystem #white {
                IAuthenticationSystem -- [UserAccountChecker]
                [SessionIdGenerator]

                UserAccountChecker --> SessionIdGenerator
            }
        }
    }

    '##------------------------------##
    '## Business Logic to Data Layer ##
    '##------------------------------##
    IUserAccDbAccess )-- UserAccountChecker

    UserAccAdministration --( IUserAccDbAccess
    ReservationDbMaintenance --( IReservationDbAccess
    RealEstateAdministration --( IReservationDbAccess
    MembershipAdministration --( IReservationDbAccess

@enduml