@startuml

'skinparam linetype ortho
skinparam linetype polyline
'skinparam monochrome true

skinparam package {
    backgroundColor lightgrey
}

package mtRooms {
    frame "Presentation Layer" #lightblue {
        package "ui" {
            component FrontDeskView #white {
                IFrontDeskController -- [FrontDeskController]
                IReservationView -- [ReservationView]
                IPaymentView -- [PaymentView]

                FrontDeskController --( IReservationView
                FrontDeskController --( IPaymentView
            }

            component AdminView #white {
                IAdminViewController -- [AdminViewController]
                IUserAccountView -- [UserAccountView]
                ICustomerAccountView -- [CustomerAccountView]

                AdminViewController --( IUserAccountView
                AdminViewController --( ICustomerAccountView
            }

            component LogisticsView #white {
                ILogisticsViewController -- [LogisticsViewController]
                ILogisticsReportView -- [LogisticsReportView]

                LogisticsViewController --( ILogisticsReportView
            }

            component RevenueView #white {
                IRevenueViewController -- [RevenueViewController]
                IInvoiceView -- [InvoiceView]
                IRevenueReportView -- [RevenueReportView]

                RevenueViewController --( IInvoiceView
                RevenueViewController --( IRevenueReportView
            }
        }
    }

    frame "network layer" #yellow {
        frame "client" #white {
            IClient -- [RmiClient]
        }

        frame RMIRegistry as RMIRegistry #white {
            interface IRmiServices
            interface IRmiClient
        }

        frame "server" #white {
            package "network" {
                [<u>:ClientWrapper] as ClientWrapper
                [<u>:RmiServer] as RmiServer
                component RmiServices
                component ClientSessions
                component EventWatcherDelegate
                IClientWrapper -- ClientWrapper

                RmiServices --( IClientWrapper
                RmiServer --|> RmiServices
                ClientWrapper *- ClientSessions
                EventWatcherDelegate *- ClientSessions
            }

        }

        ClientWrapper --( IRmiClient
        RmiServices *-- ClientSessions
        RmiClient --( IRmiServices
        RmiClient -- IRmiClient
        IRmiServices -- RmiServices
    }

    frame "Service Layer" #lightgreen {
        package "uaa" {
            ISessionDriver -- [SessionDriver]
            IAuthenticator -- [Authenticator]
            IFrontDeskDelegate -- [FrontDeskDelegate]
            IAuthenticatedFrontDesk -- [AuthenticatedFrontDesk]
            IAdministrationDelegate -- [AdministrationDelegate]
            IAuthenticatedAdministration -- [AuthenticatedAdministration]
            IRevenuePersonnelDelegate -- [RevenuePersonnelDelegate]
            IAuthenticatedRevenuePersonnel -- [AuthenticatedRevenuePersonnel]
            ILogisticsPersonnelDelegate -- [LogisticsPersonnelDelegate]
            IAuthenticatedLogisticsPersonnel -- [AuthenticatedLogisticsPersonnel]

            AuthenticatedFrontDesk --( IAuthenticator
            AuthenticatedFrontDesk --( IFrontDeskDelegate
            SessionDriver --( IAuthenticator
            AuthenticatedAdministration --( IAuthenticator
            AuthenticatedAdministration --( IAdministrationDelegate
            AuthenticatedLogisticsPersonnel --( IAuthenticator
            AuthenticatedLogisticsPersonnel --( ILogisticsPersonnelDelegate
            AuthenticatedRevenuePersonnel --( IAuthenticator
            AuthenticatedRevenuePersonnel --( IRevenuePersonnelDelegate

            SessionDriver *- AuthenticatedFrontDesk
            SessionDriver *- AuthenticatedAdministration
            SessionDriver *- AuthenticatedRevenuePersonnel
            SessionDriver *- AuthenticatedLogisticsPersonnel
        }
    }

    frame "Business Logic Layer" #orange {
        package "reservation" {
            component ReservationSystem #white {
                interface IEventWatcher
                [<u>:ReservationSession] <<Observer>> as ReservationSession
                [ScheduleCache] <<Observable>> as ScheduleCache
                [Schedule] <<Datastructure>> as Schedule

                IReservationSession -- [ReservationSession]
                IOptimisedSearch -- [OptimisedSearch]
                IReservationProcessing -- [ReservationProcessing]
                IPaymentProcessing -- [PaymentProcessing]
                ICustomerAccountAccess -- [CustomerAccountAccess]
                IScheduleCache -- [ScheduleCache]
                IScheduleChanged -- [ScheduleCache]
                IPay -- [ReservationDbDelegate]
                IReserve -- [ReservationDbDelegate]
                ISearch -- [ReservationDbDelegate]
                ICustomerAccount -- [ReservationDbDelegate]

                ScheduleCache *- Schedule
                ReservationSession -up-( IEventWatcher
                ReservationSession --( IOptimisedSearch
                ReservationSession --( IPaymentProcessing
                ReservationSession --( IReservationProcessing
                ReservationSession --( ICustomerAccountAccess
                OptimisedSearch --( IScheduleCache
                ReservationSession --( IScheduleChanged
                ReservationProcessing --( IScheduleCache

                OptimisedSearch --( ISearch
                ReservationProcessing  --( IReserve
                CustomerAccountAccess   --( ICustomerAccount
                PaymentProcessing --( IPay
            }
        }

        package "revenue" {
            component RevenueSystem #white {
                IRevenueReporter -- [ReportCreator]
                IRevenueAggregator -- [RevenueAggregator]
                IReportPrinter -- [ReportPrinter]

                ReportCreator --( IRevenueAggregator
                ReportCreator --( IReportPrinter
            }

            component InvoiceSystem #white {
                IInvoiceAggregator -- [InvoiceAggregator]
                IMailer -- [Mailer]
                IInvoice -- [InvoiceCreator]

                InvoiceCreator --( IInvoiceAggregator
                InvoiceCreator --( IMailer
            }
        }

        package "operation" {
            component LogisticsSystem #white {
                ILogisticReportGenerator -- [LogisticReportGenerator]
                ILogisticAggregator -- [LogisticAggregator]

                LogisticReportGenerator --( ILogisticAggregator
            }
        }

        package "admin" {
            component AdministrationSystem #white {
                IAdminSession -- [AdminSession]
                IUserAccAdministration -- [UserAccAdministration]
                IReservationDbMaintenance -- [ReservationDbMaintenance]

                AdminSession --( IUserAccAdministration
                AdminSession --( IReservationDbMaintenance
            }

            component AuthenticationSystem #white {
                IAuthenticationSystem -- [UserAccountChecker]
                ISessionIdGenerator -- [SessionIdGenerator]

                UserAccountChecker --( ISessionIdGenerator
            }
        }
    }

    frame "Data Layer" #purple {
        package "db" {
            component ReservationDbAccessSystem #white {
                package "database" {
                    database SQLiteDB as DB
                    IReservationDB -- [Database]
                    IUserAccDB -- [Database]
                    IReservationDB ..> IDatabase
                    IUserAccDB ..> IDatabase
                    IDatabaseBuilder -- [DatabaseBuilder]
                    IDatabaseChecker -- [DatabaseChecker]

                    [Database] -down- DB
                    [Database] --( IDatabaseBuilder
                    [Database] --( IDatabaseChecker
                }
                package "session" {
                    [<u>:SessionTracker] as SessionTracker
                    ICurrentSessions -- [SessionTracker]
                }
                IReservationDbAccess -- [ReservationDbAccess]
                IUserAccDbAccess -- [UserAccDbAccess]
                IDatabaseSystemBootstrap -- [DbSystemBootstrap]

                DbSystemBootstrap *-left- ReservationDbAccess
                DbSystemBootstrap *-right- UserAccDbAccess
                ReservationDbAccess --( ICurrentSessions
                ReservationDbAccess --( IReservationDB
                UserAccDbAccess --( IUserAccDB
                UserAccDbAccess --( ICurrentSessions
            }
        }
    }

    '##-------------------------------##
    '## Presentation to Network Layer ##
    '##-------------------------------##
'    ReservationView --( IAuthenticatedFrontDesk
'    PaymentView --( IAuthenticatedFrontDesk
'
'    UserAccountView --( IAuthenticatedAdministration
'    CustomerAccountView --( IAuthenticatedAdministration
'
'    LogisticsReportView --( IAuthenticatedLogisticsPersonnel
'
'    InvoiceView --( IAuthenticatedRevenuePersonnel
'    RevenueReportView --( IAuthenticatedRevenuePersonnel

    '##--------------------------##
    '## Network to Service Layer ##
    '##--------------------------##

    RmiServices -down-( ISessionDriver
    ClientWrapper -down-( IAuthenticatedFrontDesk
    ClientWrapper -down-( IAuthenticatedAdministration
    ClientWrapper -down-( IAuthenticatedRevenuePersonnel
    ClientWrapper -down-( IAuthenticatedLogisticsPersonnel
    EventWatcherDelegate .. IEventWatcher

    '##---------------------------------##
    '## Service to Business Logic Layer ##
    '##---------------------------------##
    AdministrationDelegate --( IAdminSession

    Authenticator --( IAuthenticationSystem

    FrontDeskDelegate --( IReservationSession

    RevenuePersonnelDelegate --( IRevenueReporter
    RevenuePersonnelDelegate --( IInvoice

    LogisticsPersonnelDelegate --( ILogisticReportGenerator

    '##------------------------------##
    '## Business Logic to Data Layer ##
    '##------------------------------##
    UserAccountChecker --( IUserAccDbAccess

    UserAccAdministration --( IUserAccDbAccess
    ReservationDbMaintenance --( IReservationDbAccess

    ReservationDbDelegate --( IReservationDbAccess

    LogisticAggregator --( IReservationDbAccess
    InvoiceAggregator --( IReservationDbAccess
    RevenueAggregator --( IReservationDbAccess
}

@enduml