@startuml

'skinparam linetype ortho
skinparam linetype polyline
'skinparam monochrome true

skinparam package {
    backgroundColor lightgrey
}


frame "Data Layer" #purple {
    package "db" {
        component ReservationDbAccessSystem #white {
            package "database" {
                database SQLiteDB as DB
                IReservationDB -- [Database]
                IUserAccDB -- [Database]
                IReservationDB ..> IDatabase
                IUserAccDB ..> IDatabase
                IDatabaseBuilder -- [DatabaseBuilder]
                IDatabaseChecker -- [DatabaseChecker]

                [Database] -down- DB
                [Database] --( IDatabaseBuilder
                [Database] --( IDatabaseChecker
            }
            package "session" {
                [<u>:SessionTracker] as SessionTracker
                ICurrentSessions -- [SessionTracker]
            }
            IReservationDbAccess -- [ReservationDbAccess]
            IUserAccDbAccess -- [UserAccDbAccess]
            IDatabaseSystemBootstrap -- [DbSystemBootstrap]

            DbSystemBootstrap *-left- ReservationDbAccess
            DbSystemBootstrap *-right- UserAccDbAccess
            ReservationDbAccess --( ICurrentSessions
            ReservationDbAccess --( IReservationDB
            UserAccDbAccess --( IUserAccDB
            UserAccDbAccess --( ICurrentSessions
        }
    }
}

@enduml