@startuml

'skinparam linetype ortho
skinparam linetype polyline
'skinparam monochrome true

skinparam package {
    backgroundColor lightgrey
}

skinparam component {
	BackgroundColor<<FXML>> LightGreen
	ArrowColor<<FXML>> DarkBlue
	BorderColor<<FXML>> DarkBlue
}

interface IClient
interface IRmiServices

frame "Presentation Layer" #lightblue {
    package "ui" {
        component MtRoomsGUI
        component SessionManager
        component Printer {

        }

        component MainWindow #white {
            component MainWindowController
            component MainWindow <<FXML>> as MainWindowView

            MainWindowController -- MainWindowView
        }

        component LoginPane #white {
            component LoginController
            component LoginView <<FXML>> as LoginView

            LoginController -- LoginView
        }

        component FrontDeskPane #white {
            component FrontDeskController
            component FrontDeskView <<FXML>> as FrontDeskView

            FrontDeskController -- FrontDeskView

            component "Customer Account" as CustAcc {
                component CustomerAccountController
                component CustomerAccountView <<FXML>> as CustomerAccountView
                component CustomerAccountAddView <<FXML>> as CustomerAccountAddView
                component CustomerAccountEditView <<FXML>> as CustomerAccountEditView

                CustomerAccountController -- CustomerAccountView
                CustomerAccountController -- CustomerAccountAddView
                CustomerAccountController -- CustomerAccountEditView
            }

            component "Search" {
                component ReservationSearchController
                component ReservationSearchView <<FXML>> as ReservationSearchView

                 ReservationSearchController -- ReservationSearchView
            }

            component Basket {
                component BasketController
                component BasketView <<FXML>> as BasketView

                BasketController -- BasketView
            }

            component Payment {
                component PaymentController
                component PaymentView <<FXML>> as PaymentView

                PaymentController -- PaymentView
            }

            component "Transaction Summary" as Summary {
                component TransactionSummaryController
                component TransactionSummaryView <<FXML>> as TransactionSummaryView

                TransactionSummaryController -- TransactionSummaryView
            }

            FrontDeskView --> CustAcc
            FrontDeskView --> Search
            FrontDeskView --> Payment
            FrontDeskView --> Summary

            Search ---> Basket
            Payment ---> Basket
            Summary ---> Basket

            FrontDeskController <... TransactionSummaryController
        }

        component AdministrationPane #white {
            component AdministrationController
            component AdministrationView <<FXML>> as AdministrationView

            component UserAdministrationTab {
                component UserAdministrationController
                component UserAdministrationView <<FXML>> as UserAdministrationView
                component AdministrationAddAccountView <<FXML>> as AdministrationAddAccountView
                component AdministrationEditAccountView <<FXML>> as AdministrationEditAccountView

                UserAdministrationController -- UserAdministrationView
                UserAdministrationController -- AdministrationAddAccountView
                UserAdministrationController -- AdministrationEditAccountView
            }
            component MaintenanceTab {
                component MaintenanceController
                component MaintenanceView <<FXML>> as MaintenanceView

                MaintenanceController --> MaintenanceView
            }

            AdministrationController -left- AdministrationView
            AdministrationView --> UserAdministrationTab
            AdministrationView --> MaintenanceTab
        }

        component LogisticsPane #white {
            component LogisticsViewController
            component LogisticsReportView <<FXML>> as LogisticsReportView

            LogisticsViewController -- LogisticsReportView
        }

        component RevenuePane #white {
            component RevenueReportController
            component RevenueView <<FXML>> as RevenueReportView

            RevenueReportController -- RevenueReportView
        }

        MainWindowController -> SessionManager
        SessionManager --( IRmiServices
        SessionManager --( IClient

        MtRoomsGUI *-down--> MainWindow
        MainWindow *-down---> LoginPane
        MainWindow *--down--> FrontDeskPane
        MainWindow *--down--> AdministrationPane
        MainWindow *--down--> LogisticsPane
        MainWindow *--down--> RevenuePane

        MtRoomsGUI *------ SessionManager
    }
}

@enduml