@startuml

'skinparam linetype ortho
skinparam linetype polyline
'skinparam monochrome true

skinparam package {
    backgroundColor lightgrey
}

frame "Service Layer" #lightgreen {
    package "uaa" {
        ISessionDriver -- [SessionDriver]
        [Authenticator]
        [FrontDeskDelegate]
        IAuthenticatedFrontDesk -- [AuthenticatedFrontDesk]
        [AdministrationDelegate]
        IAuthenticatedAdministration -- [AuthenticatedAdministration]
        [RevenuePersonnelDelegate]
        IAuthenticatedRevenuePersonnel -- [AuthenticatedRevenuePersonnel]
        [LogisticsPersonnelDelegate]
        IAuthenticatedLogisticsPersonnel -- [AuthenticatedLogisticsPersonnel]

        AuthenticatedFrontDesk --> Authenticator
        AuthenticatedFrontDesk --> FrontDeskDelegate
        SessionDriver --> Authenticator
        AuthenticatedAdministration --> Authenticator
        AuthenticatedAdministration --> AdministrationDelegate
        AuthenticatedLogisticsPersonnel --> Authenticator
        AuthenticatedLogisticsPersonnel --> LogisticsPersonnelDelegate
        AuthenticatedRevenuePersonnel --> Authenticator
        AuthenticatedRevenuePersonnel --> RevenuePersonnelDelegate

        SessionDriver *- AuthenticatedFrontDesk
        SessionDriver *- AuthenticatedAdministration
        SessionDriver *- AuthenticatedRevenuePersonnel
        SessionDriver *- AuthenticatedLogisticsPersonnel
    }
}

'##---------------------------------##
'## Service to Business Logic Layer ##
'##---------------------------------##
AdministrationDelegate --( IAdminSessionDriver

Authenticator --( IAuthenticationSystem

FrontDeskDelegate --( IReservationSessionDriver

RevenuePersonnelDelegate --( IRevenueReporter
RevenuePersonnelDelegate --( IInvoice

LogisticsPersonnelDelegate --( ILogisticReportGenerator

@enduml