@startuml

'skinparam linetype ortho
skinparam linetype polyline
'skinparam monochrome true

skinparam package {
    backgroundColor lightgrey
}

frame "Service Layer" #lightgreen {
    package "uaa" {
        IAuthenticator -- [Authenticator]
        IFrontDeskDelegate -- [FrontDeskDelegate]
        IAuthenticatedFrontDesk -- [AuthenticatedFrontDesk]
        IAdminDelegate -- [AdminDelegate]
        IAuthenticatedAdmin -- [AuthenticatedAdmin]
        IRevenuePersonnelDelegate -- [RevenuePersonnelDelegate]
        IAuthenticatedRevenuePersonnel -- [AuthenticatedRevenuePersonnel]
        ILogisticsPersonnelDelegate -- [LogisticsPersonnelDelegate]
        IAuthenticatedLogisticsPersonnel -- [AuthenticatedLogisticsPersonnel]

        AuthenticatedFrontDesk --( IAuthenticator
        AuthenticatedFrontDesk --( IFrontDeskDelegate
        AuthenticatedAdmin --( IAuthenticator
        AuthenticatedAdmin --( IAdminDelegate
        AuthenticatedLogisticsPersonnel --( IAuthenticator
        AuthenticatedLogisticsPersonnel --( ILogisticsPersonnelDelegate
        AuthenticatedRevenuePersonnel --( IAuthenticator
        AuthenticatedRevenuePersonnel --( IRevenuePersonnelDelegate
    }
}

'##---------------------------------##
'## Service to Business Logic Layer ##
'##---------------------------------##
AdminDelegate --( IAdminSession

Authenticator --( IAuthenticationSystem

FrontDeskDelegate --( IReservationSession

RevenuePersonnelDelegate --( IRevenueReporter
RevenuePersonnelDelegate --( IInvoice

LogisticsPersonnelDelegate --( ILogisticReportGenerator

@enduml