@startuml


package mtRooms {


    component BookingProcessing {
'       //TODO add the rest of the components
        [OptimisedSearch]
    }

    BookingProcessing -down-( ICustomerInfo
    BookingProcessing -down-( IPaymentProcessing
    BookingProcessing -down-( IBooking

    package {
        interface IBooking
        [Booking]
        interface ICustomerInfo
        [CustomerInfo]
        interface IPaymentProcessing
        [PaymentProcessing]
        IBooking -- Booking
        ICustomerInfo -- CustomerInfo
        IPaymentProcessing -- PaymentProcessing
    }

    package "Data" {
            interface ICustomerRecords
            interface IBookingRecords
            interface IPaymentRecords
            database Database

            ICustomerRecords -down- Database
            IBookingRecords -down- Database
            IPaymentRecords -down- Database
    }

    Booking --( IBookingRecords
    CustomerInfo --( ICustomerRecords
    PaymentProcessing --( IPaymentRecords
}

@enduml