@startuml

'skinparam linetype ortho
'skinparam linetype polyline

package mtRooms {
    package "gui" {
        [BillingView]
        [LogisticsView]
        [ReservationView]
        [PaymentView]
    }

    package "reservation" {
        interface IReservationProcess
        [ReservationProcess]
        interface IOptimisedSearch
        [OptimisedSearch]
        interface IPaymentProcessing
        [PaymentProcessing]
        interface IBooking
        interface IBookingReport
        [Booking]

        IReservationProcess -- ReservationProcess
        IOptimisedSearch -- OptimisedSearch

        ReservationProcess --( IOptimisedSearch

        IBooking -- Booking
        IBookingReport -- Booking
        IPaymentProcessing -- PaymentProcessing
    }

    package "customer" {
        interface ICustomerAccountAccess
        [CustomerAccountAccess]

        ICustomerAccountAccess -- CustomerAccountAccess
    }

    package "revenue" {
        [RevenueReportGenerator]
        interface IRevenueReportGenerator
        [InvoiceSender]
        interface IInvoiceSender

        IRevenueReportGenerator -- RevenueReportGenerator
        IInvoiceSender -- InvoiceSender
    }

    package "operation" {
        [LogisticReportGenerator]
        interface ILogisticReportGenerator

        ILogisticReportGenerator -- LogisticReportGenerator
    }

    component DB_Wrapper {
        interface IDatabase
        database Database

        IDatabase -- Database
    }
    
    interface ITimeZoneTranslation
    [TimeZoneTranslation]
    ITimeZoneTranslation -- TimeZoneTranslation
    
    DB_Wrapper --( ITimeZoneTranslation
    

    IInvoiceSender )-up- BillingView
    ILogisticReportGenerator )-up- LogisticsView
    ReservationView --( IReservationProcess
    PaymentView --( IReservationProcess

    ReservationProcess --( IPaymentProcessing
    ReservationProcess --( IBooking
    ReservationProcess --( ICustomerAccountAccess
    OptimisedSearch --( IBooking

    Booking --( IDatabase

    CustomerAccountAccess --( IDatabase
    CustomerAccountAccess --( IDatabase
    CustomerAccountAccess --( IDatabase

    PaymentProcessing --( IDatabase
    LogisticReportGenerator --( IBookingReport
    InvoiceSender --( IDatabase
    InvoiceSender --( IDatabase
    RevenueReportGenerator --( IDatabase
    RevenueReportGenerator --( IDatabase
}

@enduml