@startuml

package mtRooms {
    package "reservation" {
        interface IReservationProcess
        interface IOptimisedSearch
        interface IPaymentProcessing
        interface IReservation
        interface IReservationReport
    }

    package "customer" {
        interface ICustomerAccountAccess
    }

    package "operation" {
        interface ILogisticReportGenerator
    }

    package "revenue" {
        interface IRevenueReportGenerator
        interface IInvoiceSender
    }

    interface ITimeZoneTranslation
    interface IDatabase
}

@enduml