@startuml

package BuildingTopology {
    object Building
    object Floor
    object Room
    object Content
    object MovableContent
    object FixedContent
    object Storage
    object Chair
    object Table
    object Podium
    object WhiteBoard
    object Projector

    MovableContent -up-|> Content
    Chair -up-|> MovableContent
    Table -up-|> MovableContent
    Podium -up-|> MovableContent

    FixedContent -up-|> Content
    WhiteBoard -up-|> FixedContent
    Projector -up-|> FixedContent

    Content "0..*" -right-o "1" Room

    Floor "1..*" -down-* "1" Building
    Room "1..*" -down-* "1" Floor
    Storage -up-|> Room
}


@enduml