@startuml

Customer -down-> (Book rooms)
Customer -down-> (Modify booking)
Customer -down-> (Cancel booking)
Customer -down-> (Pay deposit)
Customer -down-> (Pay booking)

(Book rooms) -down-> Operator
(Modify booking) -down-> Operator
(Cancel booking) -down-> Operator
(Pay booking) -down-> Operator
(Pay booking) -down-> Operator

rectangle mtRooms-booking {
    Operator -down-> (Add booking)
    Operator -down-> (Edit booking)
    Operator -down-> (Remove booking)
}

rectangle mtRooms-accounts {
    Operator -down-> (Add account)
    note "Customer account \non the system" as note1
    note1 -up.. (Add account)
    note1 -up.. (Add account info)
    note1 -up.. (Edit account info)
    Operator -down-> (Add account info)
    Operator -down-> (Edit account info)
    Operator -down-> (Add payment)
    note bottom of (Add payment) : Link this to (Add booking)?
    Operator -down-> (Refund payment)
    Operator -down-> (Refund deposit)
}

:Operation Dept.: as Ops
:Accounting Dept.: as Accounting

Ops -up-> (View/Print booking sheet)
Ops -up-> (Print room display sheet)
note top of (View/Print booking sheet) : Per day/week view option?\nAlso should have requirements on it?

Accounting -up-> (View/Print payments)
note top of (View/Print payments) : Per customer/time frame/etc.. view?

@enduml